//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlyTest_PatientDetails
    {
        public int GID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> OPDID { get; set; }
        public string OPDID_Sr { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Billing_Date { get; set; }
        public string Branch { get; set; }
        public string Purpose { get; set; }
        public Nullable<decimal> Lab_Total { get; set; }
        public Nullable<decimal> Radiology_Total { get; set; }
        public Nullable<decimal> Bill_Amount { get; set; }
        public Nullable<decimal> Received { get; set; }
        public Nullable<decimal> Pending { get; set; }
        public string Patient_Name { get; set; }

        public string Doctor_Name { get; set; }
        public Nullable<decimal> Consultant_Charges { get; set; }
        public Nullable<decimal> Registration_Charges { get; set; }
        public string Update_flag { get; set; }
    }
}
